# MODEL SETTINGS

# ----> Run settings <----
case: '2016_TorreyPines_1D'

# ----> LSTM settings <----

stacked_lstm_no: 1
neuron_dropout: 0.4

# ----> Training configuration <----
optimizer: Adam
loss: MSE

batch_size: 60
sequence_length: 1
learning_rate: 0.0001
epochs: 100
num_hidden_units: 10

# ---->  Data configurations <----
target: 'dx'
shoreline: 'Shoreline'

dynamic_inputs: 
- 'Hs'
- 'Tp'

# ----> Probe settings <----
probe_target: 'omega_filt'





