# MODEL SETTINGS

# ----> Run settings <----
case: '2016_TorreyPines_1D'

# ----> LSTM settings <----

stacked_lstm_no: 1
neuron_dropout: 0.4

# ----> Training configuration <----
optimizer: Adam
loss: MSE

splits: 2 # number of intervals to split the data into
runs: 1 # number models run during training

batch_size: 20
sequence_length: 1
learning_rate: 1e-3
epochs: 40
num_hidden_units: 7

# ---->  Data configurations <----
target: 'dx'
shoreline: 'Shoreline'

dynamic_inputs: 
- 'Hs'
- 'Tp'

# ----> Probe settings <----
probe_target: 'omega_filt'





